# データ・サイエンス	データ・サイエンス社会応用論 / ICT社会応用演習Ⅳ
## 10. GTFSデータを見てみよう

### 1. 下準備
#### 1-a) ライブラリのインポート

In [77]:
import requests
import zipfile
import os
from datetime import datetime
import pandas as pd
import geopandas as gpd

#### 1-b) 定数の定義

In [78]:
GTFS_URL = 'https://api-public.odpt.org/api/v4/files/Toei/data/ToeiBus-GTFS.zip'
ZIP_PATH = 'tmp.zip'
TMPDIR_PATH = 'tmp/'

#### 1-c) データのダウンロードと展開

In [79]:
response = requests.get(GTFS_URL)

if response.status_code == 200:
  with open(ZIP_PATH, 'wb') as f:
    f.write(response.content)

if not os.path.exists(TMPDIR_PATH):
  os.makedirs(TMPDIR_PATH)

with zipfile.ZipFile(ZIP_PATH, 'r') as zip_ref:
  zip_ref.extractall(TMPDIR_PATH)

### 2. バス停の確認
#### 2-a) stops.txt の読み込み

In [80]:
df_stops = pd.read_csv(TMPDIR_PATH + 'stops.txt')
df_stops

,stop_id,stop_code,stop_name,stop_desc,stop_lat,stop_lon,zone_id,stop_url,location_type,parent_station,stop_timezone,wheelchair_boarding,platform_code
0,0001-01,NaN,愛育クリニック前,NaN,35.653697,139.726017,0001-01,https://tobus.jp/blsys/navi?LCD=&VCD=cresultrs...,0,NaN,NaN,NaN,NaN
1,0001-02,NaN,愛育クリニック前,NaN,35.654095,139.726541,0001-02,https://tobus.jp/blsys/navi?LCD=&VCD=cresultrs...,0,NaN,NaN,NaN,NaN
2,0003-01,NaN,青戸車庫前,NaN,35.744787,139.843847,0003-01,https://tobus.jp/blsys/navi?LCD=&VCD=cresultrs...,0,NaN,NaN,NaN,NaN
3,0003-02,NaN,青戸車庫前,NaN,35.745259,139.844403,0003-02,https://tobus.jp/blsys/navi?LCD=&VCD=cresultrs...,0,NaN,NaN,NaN,NaN
4,0003-03,NaN,青戸車庫前,NaN,35.743838,139.843350,0003-03,https://tobus.jp/blsys/navi?LCD=&VCD=cresultrs...,0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3717,2627-01,NaN,晴海五丁目ターミナル,NaN,35.652299,139.773363,2627-01,https://tobus.jp/blsys/navi?LCD=&VCD=cresultrs...,0,NaN,NaN,NaN,NaN
3718,2627-02,NaN,晴海五丁目ターミナル,NaN,35.652160,139.773195,2627-02,https://tobus.jp/blsys/navi?LCD=&VCD=cresultrs...,0,NaN,NaN,NaN,NaN
3719,2628-02,NaN,晴海ふ頭公園北,NaN,35.648823,139.771797,2628-02,https://tobus.jp/blsys/navi?LCD=&VCD=cresultrs...,0,NaN,NaN,NaN,NaN
3720,2629-01,NaN,晴海ふ頭公園南,NaN,35.648287,139.772342,2629-01,https://tobus.jp/blsys/navi?LCD=&VCD=cresultrs...,0,NaN,NaN,NaN,NaN
3721,3334-01,NaN,日本女子大前（豊明小学校前）,NaN,35.716309,139.719117,3334-01,https://tobus.jp/blsys/navi?LCD=&VCD=cresultrs...,0,NaN,NaN,NaN,NaN

In [81]:
df_stops[df_stops['stop_name'].str.contains('赤羽')]

,stop_id,stop_code,stop_name,stop_desc,stop_lat,stop_lon,zone_id,stop_url,location_type,parent_station,stop_timezone,wheelchair_boarding,platform_code
36,0021-01,NaN,赤羽駅東口,ＪＲ埼京線 赤羽:ＪＲ宇都宮線高崎線 赤羽:ＪＲ京浜東北線 赤羽,35.779103,139.721572,0021-01,https://tobus.jp/blsys/navi?LCD=&VCD=cresultrs...,0,NaN,NaN,NaN,NaN
37,0022-05,NaN,赤羽橋駅前,都営大江戸線 赤羽橋,35.654355,139.744270,0022-05,https://tobus.jp/blsys/navi?LCD=&VCD=cresultrs...,0,NaN,NaN,NaN,5.0
38,0022-06,NaN,赤羽橋駅前,都営大江戸線 赤羽橋,35.654181,139.744159,0022-06,https://tobus.jp/blsys/navi?LCD=&VCD=cresultrs...,0,NaN,NaN,NaN,NaN
39,0022-07,NaN,赤羽橋駅前,都営大江戸線 赤羽橋,35.654228,139.743781,0022-07,https://tobus.jp/blsys/navi?LCD=&VCD=cresultrs...,0,NaN,NaN,NaN,6.0
40,0023-01,NaN,赤羽二丁目,東京メトロ南北線 赤羽岩淵,35.782227,139.722378,0023-01,https://tobus.jp/blsys/navi?LCD=&VCD=cresultrs...,0,NaN,NaN,NaN,NaN
41,0023-02,NaN,赤羽二丁目,東京メトロ南北線 赤羽岩淵,35.782832,139.722613,0023-02,https://tobus.jp/blsys/navi?LCD=&VCD=cresultrs...,0,NaN,NaN,NaN,NaN
3673,2584-01,NaN,赤羽橋交差点,NaN,35.655808,139.744836,2584-01,https://tobus.jp/blsys/navi?LCD=&VCD=cresultrs...,0,NaN,NaN,NaN,4.0
3674,2584-02,NaN,赤羽橋交差点,NaN,35.655898,139.745138,2584-02,https://tobus.jp/blsys/navi?LCD=&VCD=cresultrs...,0,NaN,NaN,NaN,3.0

#### 2-b) GeoPandasでの読み込み

In [82]:
gdf_stops = gpd.GeoDataFrame(df_stops, geometry=gpd.points_from_xy(df_stops['stop_lon'], df_stops['stop_lat'], crs=4326))
gdf_stops

,stop_id,stop_code,stop_name,stop_desc,stop_lat,stop_lon,zone_id,stop_url,location_type,parent_station,stop_timezone,wheelchair_boarding,platform_code,geometry
0,0001-01,NaN,愛育クリニック前,NaN,35.653697,139.726017,0001-01,https://tobus.jp/blsys/navi?LCD=&VCD=cresultrs...,0,NaN,NaN,NaN,NaN,POINT (139.72602 35.65370)
1,0001-02,NaN,愛育クリニック前,NaN,35.654095,139.726541,0001-02,https://tobus.jp/blsys/navi?LCD=&VCD=cresultrs...,0,NaN,NaN,NaN,NaN,POINT (139.72654 35.65409)
2,0003-01,NaN,青戸車庫前,NaN,35.744787,139.843847,0003-01,https://tobus.jp/blsys/navi?LCD=&VCD=cresultrs...,0,NaN,NaN,NaN,NaN,POINT (139.84385 35.74479)
3,0003-02,NaN,青戸車庫前,NaN,35.745259,139.844403,0003-02,https://tobus.jp/blsys/navi?LCD=&VCD=cresultrs...,0,NaN,NaN,NaN,NaN,POINT (139.84440 35.74526)
4,0003-03,NaN,青戸車庫前,NaN,35.743838,139.843350,0003-03,https://tobus.jp/blsys/navi?LCD=&VCD=cresultrs...,0,NaN,NaN,NaN,NaN,POINT (139.84335 35.74384)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3717,2627-01,NaN,晴海五丁目ターミナル,NaN,35.652299,139.773363,2627-01,https://tobus.jp/blsys/navi?LCD=&VCD=cresultrs...,0,NaN,NaN,NaN,NaN,POINT (139.77336 35.65230)
3718,2627-02,NaN,晴海五丁目ターミナル,NaN,35.652160,139.773195,2627-02,https://tobus.jp/blsys/navi?LCD=&VCD=cresultrs...,0,NaN,NaN,NaN,NaN,POINT (139.77319 35.65216)
3719,2628-02,NaN,晴海ふ頭公園北,NaN,35.648823,139.771797,2628-02,https://tobus.jp/blsys/navi?LCD=&VCD=cresultrs...,0,NaN,NaN,NaN,NaN,POINT (139.77180 35.64882)
3720,2629-01,NaN,晴海ふ頭公園南,NaN,35.648287,139.772342,2629-01,https://tobus.jp/blsys/navi?LCD=&VCD=cresultrs...,0,NaN,NaN,NaN,NaN,POINT (139.77234 35.64829)
3721,3334-01,NaN,日本女子大前（豊明小学校前）,NaN,35.716309,139.719117,3334-01,https://tobus.jp/blsys/navi?LCD=&VCD=cresultrs...,0,NaN,NaN,NaN,NaN,POINT (139.71912 35.71631)

In [83]:
gdf_stops[df_stops['stop_name'].str.contains('赤羽')].explore(marker_type='circle')

### 3. バス路線の確認
#### 3-a) routes.txt の読み込み

In [84]:
df_routes = pd.read_csv(TMPDIR_PATH + 'routes.txt')
df_routes

,route_id,agency_id,route_short_name,route_long_name,route_desc,route_type,route_url,route_color,route_text_color,jp_parent_route_id
0,2,8000020130001,波０１（ＮＭ０１）,NaN,NaN,3,https://tobus.jp/blsys/navi?VCD=cresultapr&ECD...,F1B34E,350800,NaN
1,3,8000020130001,市０１,NaN,NaN,3,https://tobus.jp/blsys/navi?VCD=cresultapr&ECD...,B779B7,FAF6FB,NaN
2,6,8000020130001,都０１（Ｔ０１）,NaN,NaN,3,https://tobus.jp/blsys/navi?VCD=cresultapr&ECD...,00A9E8,FFFFFF,NaN
3,8,8000020130001,ＲＨ０１,NaN,NaN,3,https://tobus.jp/blsys/navi?VCD=cresultapr&ECD...,BB7AAA,FFFFFF,NaN
4,10,8000020130001,ＣＨ０１,NaN,NaN,3,https://tobus.jp/blsys/navi?VCD=cresultapr&ECD...,E90087,FFF0FF,NaN
...,...,...,...,...,...,...,...,...,...,...
159,286,8000020130001,梅７７甲,NaN,NaN,3,https://tobus.jp/blsys/navi?VCD=cresultapr&ECD...,77BC2D,FFFFFF,NaN
160,287,8000020130001,梅７７乙,NaN,NaN,3,https://tobus.jp/blsys/navi?VCD=cresultapr&ECD...,8649A7,FFFFFF,NaN
161,288,8000020130001,梅７７丙,NaN,NaN,3,https://tobus.jp/blsys/navi?VCD=cresultapr&ECD...,B08B5B,FFFFFF,NaN
162,289,8000020130001,梅７７丁,NaN,NaN,3,https://tobus.jp/blsys/navi?VCD=cresultapr&ECD...,EB6C78,FFFFFF,NaN
163,291,8000020130001,梅０１,NaN,NaN,3,https://tobus.jp/blsys/navi?VCD=cresultapr&ECD...,7B6FAE,FFFFFF,NaN

#### 3-b) trips.txt の読み込み

In [85]:
df_trips = pd.read_csv(TMPDIR_PATH + 'trips.txt')
df_trips[df_trips['trip_headsign'] == '赤羽駅東口']

,route_id,service_id,trip_id,trip_headsign,trip_short_name,direction_id,block_id,shape_id,wheelchair_accessible,bikes_allowed,jp_trip_desc,jp_trip_desc_symbol,jp_office_id
26582,119,49-100,40301-2-49-100-0600,赤羽駅東口,NaN,0.0,NaN,40301-2,1,0,NaN,NaN,49
26583,119,49-100,40301-2-49-100-0635,赤羽駅東口,NaN,0.0,NaN,40301-2,1,0,NaN,NaN,49
26584,119,49-100,40301-2-49-100-0704,赤羽駅東口,NaN,0.0,NaN,40301-2,1,0,NaN,NaN,49
26585,119,49-100,40301-2-49-100-0730,赤羽駅東口,NaN,0.0,NaN,40301-2,1,0,NaN,NaN,49
26586,119,49-100,40301-2-49-100-0752,赤羽駅東口,NaN,0.0,NaN,40301-2,1,0,NaN,NaN,49
...,...,...,...,...,...,...,...,...,...,...,...,...,...
26812,119,49-300,40301-2-49-300-2046,赤羽駅東口,NaN,0.0,NaN,40301-2,1,0,NaN,NaN,49
26813,119,49-300,40301-2-49-300-2114,赤羽駅東口,NaN,0.0,NaN,40301-2,1,0,NaN,NaN,49
26814,119,49-300,40301-2-49-300-2143,赤羽駅東口,NaN,0.0,NaN,40301-2,1,0,NaN,NaN,49
26815,119,49-300,40301-2-49-300-2212,赤羽駅東口,NaN,0.0,NaN,40301-2,1,0,NaN,NaN,49
26816,119,49-300,40301-2-49-300-2235,赤羽駅東口,NaN,0.0,NaN,40301-2,1,0,NaN,NaN,49

#### 3-c) stop_times.txt の読み込み

In [86]:
df_stop_times = pd.read_csv(TMPDIR_PATH + 'stop_times.txt')
df_stop_times

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,stop_headsign,pickup_type,drop_off_type,shape_dist_traveled,timepoint
0,00106-1-01-105-0913,09:13:00,09:13:00,0737-01,1,豊洲市場,NaN,NaN,NaN,1
1,00106-1-01-105-0913,09:14:00,09:14:00,1239-01,2,豊洲市場,NaN,NaN,NaN,1
2,00106-1-01-105-0913,09:16:00,09:16:00,2024-01,3,豊洲市場,NaN,NaN,NaN,1
3,00106-1-01-105-0913,09:18:00,09:18:00,2579-01,4,豊洲市場,NaN,NaN,NaN,1
4,00106-1-01-105-0913,09:21:00,09:21:00,0946-02,5,豊洲市場,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...
1186006,74601-2-81-301-2000,20:32:00,20:32:00,0594-01,15,東陽町駅前,NaN,NaN,NaN,1
1186007,74601-2-81-301-2000,20:35:00,20:35:00,2003-02,16,東陽町駅前,NaN,NaN,NaN,1
1186008,74601-2-81-301-2000,20:36:00,20:36:00,2587-02,17,東陽町駅前,NaN,NaN,NaN,1
1186009,74601-2-81-301-2000,20:37:00,20:37:00,2592-02,18,東陽町駅前,NaN,NaN,NaN,1
1186010,74601-2-81-301-2000,20:43:00,20:43:00,0989-08,19,東陽町駅前,NaN,NaN,NaN,1

#### 3-d) マージ

In [87]:
df_merged = df_routes.merge(df_trips).merge(df_stop_times).merge(df_stops)
df_merged

,route_id,agency_id,route_short_name,route_long_name,route_desc,route_type,route_url,route_color,route_text_color,jp_parent_route_id,...,stop_desc,stop_lat,stop_lon,zone_id,stop_url,location_type,parent_station,stop_timezone,wheelchair_boarding,platform_code
0,2,8000020130001,波０１（ＮＭ０１）,NaN,NaN,3,https://tobus.jp/blsys/navi?VCD=cresultapr&ECD...,F1B34E,350800,NaN,...,りんかい線 東京テレポート,35.627171,139.779406,2326-05,https://tobus.jp/blsys/navi?LCD=&VCD=cresultrs...,0,NaN,NaN,NaN,3.0
1,2,8000020130001,波０１（ＮＭ０１）,NaN,NaN,3,https://tobus.jp/blsys/navi?VCD=cresultapr&ECD...,F1B34E,350800,NaN,...,ゆりかもめ 東京国際クルーズターミナル,35.621057,139.774762,0302-03,https://tobus.jp/blsys/navi?LCD=&VCD=cresultrs...,0,NaN,NaN,NaN,NaN
2,2,8000020130001,波０１（ＮＭ０１）,NaN,NaN,3,https://tobus.jp/blsys/navi?VCD=cresultapr&ECD...,F1B34E,350800,NaN,...,NaN,35.618961,139.775240,2546-01,https://tobus.jp/blsys/navi?LCD=&VCD=cresultrs...,0,NaN,NaN,NaN,NaN
3,2,8000020130001,波０１（ＮＭ０１）,NaN,NaN,3,https://tobus.jp/blsys/navi?VCD=cresultapr&ECD...,F1B34E,350800,NaN,...,NaN,35.617548,139.776382,2407-04,https://tobus.jp/blsys/navi?LCD=&VCD=cresultrs...,0,NaN,NaN,NaN,4.0
4,2,8000020130001,波０１（ＮＭ０１）,NaN,NaN,3,https://tobus.jp/blsys/navi?VCD=cresultapr&ECD...,F1B34E,350800,NaN,...,ゆりかもめ テレコムセンター,35.617403,139.778878,2327-01,https://tobus.jp/blsys/navi?LCD=&VCD=cresultrs...,0,NaN,NaN,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1186006,291,8000020130001,梅０１,NaN,NaN,3,https://tobus.jp/blsys/navi?VCD=cresultapr&ECD...,7B6FAE,FFFFFF,NaN,...,NaN,35.785713,139.249676,1441-02,https://tobus.jp/blsys/navi?LCD=&VCD=cresultrs...,0,NaN,NaN,NaN,NaN
1186007,291,8000020130001,梅０１,NaN,NaN,3,https://tobus.jp/blsys/navi?VCD=cresultapr&ECD...,7B6FAE,FFFFFF,NaN,...,NaN,35.786220,139.251875,0255-02,https://tobus.jp/blsys/navi?LCD=&VCD=cresultrs...,0,NaN,NaN,NaN,NaN
1186008,291,8000020130001,梅０１,NaN,NaN,3,https://tobus.jp/blsys/navi?VCD=cresultapr&ECD...,7B6FAE,FFFFFF,NaN,...,NaN,35.787518,139.254224,0876-02,https://tobus.jp/blsys/navi?LCD=&VCD=cresultrs...,0,NaN,NaN,NaN,NaN
1186009,291,8000020130001,梅０１,NaN,NaN,3,https://tobus.jp/blsys/navi?VCD=cresultapr&ECD...,7B6FAE,FFFFFF,NaN,...,NaN,35.789953,139.255373,1080-01,https://tobus.jp/blsys/navi?LCD=&VCD=cresultrs...,0,NaN,NaN,NaN,NaN
1186010,291,8000020130001,梅０１,NaN,NaN,3,https://tobus.jp/blsys/navi?VCD=cresultapr&ECD...,7B6FAE,FFFFFF,NaN,...,ＪＲ青梅線 青梅,35.790169,139.257960,0202-01,https://tobus.jp/blsys/navi?LCD=&VCD=cresultrs...,0,NaN,NaN,NaN,3.0

#### 4. 運行日の確認
#### 4-a) calendar.txt の読み込み

In [88]:
df_calendar = pd.read_csv(TMPDIR_PATH + 'calendar.txt')
df_calendar

,service_id,monday,tuesday,wednesday,thursday,friday,saturday,sunday,start_date,end_date
0,01-100,0,0,0,0,0,0,1,20241211,20271210
1,01-160,0,0,0,0,0,1,0,20241211,20271210
2,01-170,1,1,1,1,1,0,0,20241211,20271210
3,06-100,0,0,0,0,0,0,1,20241211,20271210
4,06-160,0,0,0,0,0,1,0,20241211,20271210
5,06-170,1,1,1,1,1,0,0,20241211,20271210
6,09-100,0,0,0,0,0,0,1,20241211,20271210
7,09-160,0,0,0,0,0,1,0,20241211,20271210
8,09-170,1,1,1,1,1,0,0,20241211,20271210
9,13-100,0,0,0,0,0,0,1,20241211,20271210
10,13-160,0,0,0,0,0,1,0,20241211,20271210
11,13-170,1,1,1,1,1,0,0,20241211,20271210
12,21-100,0,0,0,0,0,0,1,20241211,20271210
13,21-160,0,0,0,0,0,1,0,20241211,20271210
14,21-170,1,1,1,1,1,0,0,20241211,20271210
15,25-100,0,0,0,0,0,0,1,20241211,20271210
16,25-160,0,0,0,0,0,1,0,20241211,20271210
17,25-170,1,1,1,1,1,0,0,20241211,20271210
18,29-100,0,0,0,0,0,0,1,20241211,20271210
19,29-160,0,0,0,0,0,1,0,20241211,20271210
20,29-170,1,1,1,1,1,0,0,20241211,20271210
21,33-100,0,0,0,0,0,0,1,20241211,20271210
22,33-160,0,0,0,0,0,1,0,20241211,20271210
23,33-170,1,1,1,1,1,0,0,20241211,20271210
24,37-100,0,0,0,0,0,0,1,20241211,20271210
25,37-160,0,0,0,0,0,1,0,20241211,20271210
26,37-170,1,1,1,1,1,0,0,20241211,20271210
27,41-100,0,0,0,0,0,0,1,20241211,20271210
28,41-160,0,0,0,0,0,1,0,20241211,20271210
29,41-170,1,1,1,1,1,0,0,20241211,20271210
30,45-100,0,0,0,0,0,0,1,20241211,20271210
31,45-160,0,0,0,0,0,1,0,20241211,20271210
32,45-170,1,1,1,1,1,0,0,20241211,20271210
33,49-100,0,0,0,0,0,0,1,20241211,20271210
34,49-160,0,0,0,0,0,1,0,20241211,20271210
35,49-170,1,1,1,1,1,0,0,20241211,20271210
36,53-100,0,0,0,0,0,0,1,20241211,20271210
37,53-160,0,0,0,0,0,1,0,20241211,20271210
38,53-170,1,1,1,1,1,0,0,20241211,20271210
39,57-100,0,0,0,0,0,0,1,20241211,20271210
40,57-160,0,0,0,0,0,1,0,20241211,20271210
41,57-170,1,1,1,1,1,0,0,20241211,20271210
42,61-100,0,0,0,0,0,0,1,20241211,20271210
43,61-160,0,0,0,0,0,1,0,20241211,20271210
44,61-170,1,1,1,1,1,0,0,20241211,20271210
45,65-100,0,0,0,0,0,0,1,20241211,20271210
46,65-160,0,0,0,0,0,1,0,20241211,20271210
47,65-170,1,1,1,1,1,0,0,20241211,20271210
48,69-100,0,0,0,0,0,0,1,20241211,20271210
49,69-160,0,0,0,0,0,1,0,20241211,20271210
50,69-170,1,1,1,1,1,0,0,20241211,20271210
51,77-100,0,0,0,0,0,0,1,20241211,20271210
52,77-160,0,0,0,0,0,1,0,20241211,20271210
53,77-170,1,1,1,1,1,0,0,20241211,20271210
54,81-100,0,0,0,0,0,0,1,20241211,20271210
55,81-160,0,0,0,0,0,1,0,20241211,20271210
56,81-170,1,1,1,1,1,0,0,20241211,20271210
57,85-100,0,0,0,0,0,0,1,20241211,20271210
58,85-160,0,0,0,0,0,1,0,20241211,20271210
59,85-170,1,1,1,1,1,0,0,20241211,20271210

#### 4-b) calendar_dates.txt の読み込み

In [89]:
df_calendar_dates = pd.read_csv(TMPDIR_PATH + 'calendar_dates.txt')
df_calendar_dates

    service_id      date  exception_type
0       01-179  20241211               1
1       01-170  20241211               2
2       81-179  20241211               1
3       81-170  20241211               2
4       09-172  20241213               1
..         ...       ...             ...
313     81-170  20250122               2
314     81-179  20250129               1
315     81-170  20250129               2
316     81-179  20250205               1
317     81-170  20250205               2

[318 rows x 3 columns]

### 5. 木曜日のデータの確認
#### 5-a) 木曜日の運行便の確認

In [90]:
services = set(df_calendar[df_calendar['sunday'] == 1]['service_id'])
services

{'01-100',
 '06-100',
 '09-100',
 '13-100',
 '21-100',
 '25-100',
 '29-100',
 '33-100',
 '37-100',
 '41-100',
 '45-100',
 '49-100',
 '53-100',
 '57-100',
 '61-100',
 '65-100',
 '69-100',
 '77-100',
 '81-100',
 '85-100'}

In [91]:
df_route_trips = df_routes.merge(df_trips)
df_route_trips_today = df_route_trips[df_route_trips['service_id'].isin(services)]
df_route_trips_today

,route_id,agency_id,route_short_name,route_long_name,route_desc,route_type,route_url,route_color,route_text_color,jp_parent_route_id,...,trip_headsign,trip_short_name,direction_id,block_id,shape_id,wheelchair_accessible,bikes_allowed,jp_trip_desc,jp_trip_desc_symbol,jp_office_id
0,2,8000020130001,波０１（ＮＭ０１）,NaN,NaN,3,https://tobus.jp/blsys/navi?VCD=cresultapr&ECD...,F1B34E,350800,NaN,...,中央防波堤,NaN,1.0,NaN,04601-1,1,0,NaN,NaN,85
122,2,8000020130001,波０１（ＮＭ０１）,NaN,NaN,3,https://tobus.jp/blsys/navi?VCD=cresultapr&ECD...,F1B34E,350800,NaN,...,東京テレポート駅前,NaN,0.0,NaN,04601-2,1,0,NaN,NaN,85
547,6,8000020130001,都０１（Ｔ０１）,NaN,NaN,3,https://tobus.jp/blsys/navi?VCD=cresultapr&ECD...,00A9E8,FFFFFF,NaN,...,新橋駅前,NaN,1.0,NaN,08501-1,1,0,NaN,NaN,9
548,6,8000020130001,都０１（Ｔ０１）,NaN,NaN,3,https://tobus.jp/blsys/navi?VCD=cresultapr&ECD...,00A9E8,FFFFFF,NaN,...,新橋駅前,NaN,1.0,NaN,08501-1,1,0,NaN,NaN,9
549,6,8000020130001,都０１（Ｔ０１）,NaN,NaN,3,https://tobus.jp/blsys/navi?VCD=cresultapr&ECD...,00A9E8,FFFFFF,NaN,...,新橋駅前,NaN,1.0,NaN,08501-1,1,0,NaN,NaN,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61602,291,8000020130001,梅０１,NaN,NaN,3,https://tobus.jp/blsys/navi?VCD=cresultapr&ECD...,7B6FAE,FFFFFF,NaN,...,青梅駅前,NaN,NaN,NaN,29101-3,1,0,NaN,NaN,25
61603,291,8000020130001,梅０１,NaN,NaN,3,https://tobus.jp/blsys/navi?VCD=cresultapr&ECD...,7B6FAE,FFFFFF,NaN,...,青梅駅前,NaN,NaN,NaN,29101-3,1,0,NaN,NaN,25
61604,291,8000020130001,梅０１,NaN,NaN,3,https://tobus.jp/blsys/navi?VCD=cresultapr&ECD...,7B6FAE,FFFFFF,NaN,...,青梅駅前,NaN,NaN,NaN,29101-3,1,0,NaN,NaN,25
61605,291,8000020130001,梅０１,NaN,NaN,3,https://tobus.jp/blsys/navi?VCD=cresultapr&ECD...,7B6FAE,FFFFFF,NaN,...,青梅駅前,NaN,NaN,NaN,29101-3,1,0,NaN,NaN,25
61606,291,8000020130001,梅０１,NaN,NaN,3,https://tobus.jp/blsys/navi?VCD=cresultapr&ECD...,7B6FAE,FFFFFF,NaN,...,青梅駅前,NaN,NaN,NaN,29101-3,1,0,NaN,NaN,25

In [92]:
df_route_trips_today[df_route_trips_today['route_short_name'] == '王']

Empty DataFrame
Columns: [route_id, agency_id, route_short_name, route_long_name, route_desc, route_type, route_url, route_color, route_text_color, jp_parent_route_id, service_id, trip_id, trip_headsign, trip_short_name, direction_id, block_id, shape_id, wheelchair_accessible, bikes_allowed, jp_trip_desc, jp_trip_desc_symbol, jp_office_id]
Index: []

[0 rows x 22 columns]

##### 5-b) 発着時刻の確認

In [93]:
df_merged_today = df_route_trips_today.merge(df_stop_times)
df_merged_today

,route_id,agency_id,route_short_name,route_long_name,route_desc,route_type,route_url,route_color,route_text_color,jp_parent_route_id,...,jp_office_id,arrival_time,departure_time,stop_id,stop_sequence,stop_headsign,pickup_type,drop_off_type,shape_dist_traveled,timepoint
0,2,8000020130001,波０１（ＮＭ０１）,NaN,NaN,3,https://tobus.jp/blsys/navi?VCD=cresultapr&ECD...,F1B34E,350800,NaN,...,85,09:03:00,09:03:00,2326-05,1,中央防波堤,NaN,NaN,NaN,1
1,2,8000020130001,波０１（ＮＭ０１）,NaN,NaN,3,https://tobus.jp/blsys/navi?VCD=cresultapr&ECD...,F1B34E,350800,NaN,...,85,09:03:00,09:03:00,0302-03,2,中央防波堤,NaN,NaN,NaN,1
2,2,8000020130001,波０１（ＮＭ０１）,NaN,NaN,3,https://tobus.jp/blsys/navi?VCD=cresultapr&ECD...,F1B34E,350800,NaN,...,85,09:04:00,09:04:00,2546-01,3,中央防波堤,NaN,NaN,NaN,1
3,2,8000020130001,波０１（ＮＭ０１）,NaN,NaN,3,https://tobus.jp/blsys/navi?VCD=cresultapr&ECD...,F1B34E,350800,NaN,...,85,09:05:00,09:05:00,2407-04,4,中央防波堤,NaN,NaN,NaN,1
4,2,8000020130001,波０１（ＮＭ０１）,NaN,NaN,3,https://tobus.jp/blsys/navi?VCD=cresultapr&ECD...,F1B34E,350800,NaN,...,85,09:08:00,09:08:00,2327-01,5,中央防波堤,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247459,291,8000020130001,梅０１,NaN,NaN,3,https://tobus.jp/blsys/navi?VCD=cresultapr&ECD...,7B6FAE,FFFFFF,NaN,...,25,16:42:00,16:42:00,1441-02,46,青梅駅前,NaN,NaN,NaN,1
247460,291,8000020130001,梅０１,NaN,NaN,3,https://tobus.jp/blsys/navi?VCD=cresultapr&ECD...,7B6FAE,FFFFFF,NaN,...,25,16:42:00,16:42:00,0255-02,47,青梅駅前,NaN,NaN,NaN,1
247461,291,8000020130001,梅０１,NaN,NaN,3,https://tobus.jp/blsys/navi?VCD=cresultapr&ECD...,7B6FAE,FFFFFF,NaN,...,25,16:43:00,16:43:00,0876-02,48,青梅駅前,NaN,NaN,NaN,1
247462,291,8000020130001,梅０１,NaN,NaN,3,https://tobus.jp/blsys/navi?VCD=cresultapr&ECD...,7B6FAE,FFFFFF,NaN,...,25,16:44:00,16:44:00,1080-01,49,青梅駅前,NaN,NaN,NaN,1
247463,291,8000020130001,梅０１,NaN,NaN,3,https://tobus.jp/blsys/navi?VCD=cresultapr&ECD...,7B6FAE,FFFFFF,NaN,...,25,16:48:00,16:48:00,0202-01,50,青梅駅前,NaN,NaN,NaN,1

In [99]:
df_merged_today[df_merged_today['service_id'] == '49-100'].sort_values('departure_time')

,route_id,agency_id,route_short_name,route_long_name,route_desc,route_type,route_url,route_color,route_text_color,jp_parent_route_id,...,jp_office_id,arrival_time,departure_time,stop_id,stop_sequence,stop_headsign,pickup_type,drop_off_type,shape_dist_traveled,timepoint
158807,119,8000020130001,王５７,NaN,NaN,3,https://tobus.jp/blsys/navi?VCD=cresultapr&ECD...,267B6B,FFFFFF,NaN,...,49,06:00:00,06:00:00,1004-03,1,赤羽駅東口,NaN,NaN,NaN,1
158808,119,8000020130001,王５７,NaN,NaN,3,https://tobus.jp/blsys/navi?VCD=cresultapr&ECD...,267B6B,FFFFFF,NaN,...,49,06:01:00,06:01:00,1007-01,2,赤羽駅東口,NaN,NaN,NaN,1
158809,119,8000020130001,王５７,NaN,NaN,3,https://tobus.jp/blsys/navi?VCD=cresultapr&ECD...,267B6B,FFFFFF,NaN,...,49,06:01:00,06:01:00,1003-02,3,赤羽駅東口,NaN,NaN,NaN,1
158810,119,8000020130001,王５７,NaN,NaN,3,https://tobus.jp/blsys/navi?VCD=cresultapr&ECD...,267B6B,FFFFFF,NaN,...,49,06:02:00,06:02:00,1002-01,4,赤羽駅東口,NaN,NaN,NaN,1
158811,119,8000020130001,王５７,NaN,NaN,3,https://tobus.jp/blsys/navi?VCD=cresultapr&ECD...,267B6B,FFFFFF,NaN,...,49,06:03:00,06:03:00,1001-01,5,赤羽駅東口,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160014,119,8000020130001,王５７,NaN,NaN,3,https://tobus.jp/blsys/navi?VCD=cresultapr&ECD...,267B6B,FFFFFF,NaN,...,49,23:07:00,23:07:00,1001-02,2,豊島五丁目団地,NaN,NaN,NaN,1
160016,119,8000020130001,王５７,NaN,NaN,3,https://tobus.jp/blsys/navi?VCD=cresultapr&ECD...,267B6B,FFFFFF,NaN,...,49,23:08:00,23:08:00,1003-01,4,豊島五丁目団地,NaN,NaN,NaN,1
160015,119,8000020130001,王５７,NaN,NaN,3,https://tobus.jp/blsys/navi?VCD=cresultapr&ECD...,267B6B,FFFFFF,NaN,...,49,23:08:00,23:08:00,1002-02,3,豊島五丁目団地,NaN,NaN,NaN,1
160017,119,8000020130001,王５７,NaN,NaN,3,https://tobus.jp/blsys/navi?VCD=cresultapr&ECD...,267B6B,FFFFFF,NaN,...,49,23:09:00,23:09:00,1007-02,5,豊島五丁目団地,NaN,NaN,NaN,1
160018,119,8000020130001,王５７,NaN,NaN,3,https://tobus.jp/blsys/navi?VCD=cresultapr&ECD...,267B6B,FFFFFF,NaN,...,49,23:12:00,23:12:00,1004-04,6,豊島五丁目団地,NaN,NaN,NaN,1